//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbd.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tbd.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _Add 的本地化字符串。
        /// </summary>
        internal static string addButton_Content {
            get {
                return ResourceManager.GetString("addButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow clients from LAN 的本地化字符串。
        /// </summary>
        internal static string AllowClientsFromLAN {
            get {
                return ResourceManager.GetString("AllowClientsFromLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Cancel 的本地化字符串。
        /// </summary>
        internal static string cancelButton_Content {
            get {
                return ResourceManager.GetString("cancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Copy link 的本地化字符串。
        /// </summary>
        internal static string copyLinkButton_Content {
            get {
                return ResourceManager.GetString("copyLinkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credentials (optional) 的本地化字符串。
        /// </summary>
        internal static string CredentialsOptional {
            get {
                return ResourceManager.GetString("CredentialsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward Proxy 的本地化字符串。
        /// </summary>
        internal static string ForwardProxy {
            get {
                return ResourceManager.GetString("ForwardProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP 的本地化字符串。
        /// </summary>
        internal static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No proxy 的本地化字符串。
        /// </summary>
        internal static string NoProxy {
            get {
                return ResourceManager.GetString("NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Not now 的本地化字符串。
        /// </summary>
        internal static string notNowButton_Content {
            get {
                return ResourceManager.GetString("notNowButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        internal static string okButton_Content {
            get {
                return ResourceManager.GetString("okButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Configuration Delivery 的本地化字符串。
        /// </summary>
        internal static string OnlineConfigDelivery {
            get {
                return ResourceManager.GetString("OnlineConfigDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open logs window 的本地化字符串。
        /// </summary>
        internal static string OpenLogsWindow {
            get {
                return ResourceManager.GetString("OpenLogsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Register all 的本地化字符串。
        /// </summary>
        internal static string registerAllButton_Content {
            get {
                return ResourceManager.GetString("registerAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register hotkeys at startup 的本地化字符串。
        /// </summary>
        internal static string RegisterHotkeysAtStartup {
            get {
                return ResourceManager.GetString("RegisterHotkeysAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string removeButton_Content {
            get {
                return ResourceManager.GetString("removeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        internal static string saveButton_Content {
            get {
                return ResourceManager.GetString("saveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Sharing 的本地化字符串。
        /// </summary>
        internal static string ServerSharing {
            get {
                return ResourceManager.GetString("ServerSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following sources failed to update:\n\n 的本地化字符串。
        /// </summary>
        internal static string sip008UpdateAllFailure {
            get {
                return ResourceManager.GetString("sip008UpdateAllFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully updated all sources! 的本地化字符串。
        /// </summary>
        internal static string sip008UpdateAllSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed. See the logs for more information. 的本地化字符串。
        /// </summary>
        internal static string sip008UpdateFailure {
            get {
                return ResourceManager.GetString("sip008UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully updated the selected source! 的本地化字符串。
        /// </summary>
        internal static string sip008UpdateSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Skip version 的本地化字符串。
        /// </summary>
        internal static string skipVersionButton_Content {
            get {
                return ResourceManager.GetString("skipVersionButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOCKS5 的本地化字符串。
        /// </summary>
        internal static string SOCKS5 {
            get {
                return ResourceManager.GetString("SOCKS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to next server 的本地化字符串。
        /// </summary>
        internal static string SwitchToNextServer {
            get {
                return ResourceManager.GetString("SwitchToNextServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to previous server 的本地化字符串。
        /// </summary>
        internal static string SwitchToPreviousServer {
            get {
                return ResourceManager.GetString("SwitchToPreviousServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout (sec) 的本地化字符串。
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle proxy mode 的本地化字符串。
        /// </summary>
        internal static string ToggleProxyMode {
            get {
                return ResourceManager.GetString("ToggleProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle system proxy 的本地化字符串。
        /// </summary>
        internal static string ToggleSystemProxy {
            get {
                return ResourceManager.GetString("ToggleSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update all 的本地化字符串。
        /// </summary>
        internal static string updateAllButton_Content {
            get {
                return ResourceManager.GetString("updateAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Update 的本地化字符串。
        /// </summary>
        internal static string updateButton_Content {
            get {
                return ResourceManager.GetString("updateButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please read the release notes carefully. Then decide whether to update. 的本地化字符串。
        /// </summary>
        internal static string updatePromptBody {
            get {
                return ResourceManager.GetString("updatePromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An update is available. 的本地化字符串。
        /// </summary>
        internal static string updatePromptTitle {
            get {
                return ResourceManager.GetString("updatePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VersionUpdate 的本地化字符串。
        /// </summary>
        internal static string VersionUpdate {
            get {
                return ResourceManager.GetString("VersionUpdate", resourceCulture);
            }
        }
    }
}
